#!/usr/bin/env bash
# sync-versions.sh — generate etc/versions.env from etc/deps.yaml.
# deps.yaml is the SINGLE SOURCE OF TRUTH; this produces the runtime
# versions.env that install.sh copies to MINIONS_HOME and lib scripts source.
#
# Usage: scripts/sync-versions.sh [--check]
#   --check: exit non-zero if versions.env would differ (CI guard).

set -u
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEPS_YAML="${DEPS_YAML:-${REPO_ROOT}/etc/deps.yaml}"
VERSIONS_ENV="${VERSIONS_ENV:-${REPO_ROOT}/etc/versions.env}"

[ -f "${DEPS_YAML}" ] || { echo "missing ${DEPS_YAML}" >&2; exit 1; }

# Generate versions.env content via python3 (yaml module).
generated="$(python3 - "${DEPS_YAML}" <<'PY'
import sys, yaml
data = yaml.safe_load(open(sys.argv[1]))
lines = []
lines.append('# .minions component version lockfile')
lines.append('# Auto-generated by sync-versions.sh from etc/deps.yaml')
lines.append('# Do not edit manually — edit etc/deps.yaml instead')
lines.append('')
for dep in data['dependencies']:
    name = dep['name']
    ver = dep['version']
    lines.append(f'{name}_VERSION="{ver}"')
    sha = dep.get('sha256', {})
    for platform in dep.get('platforms', []):
        pu = platform.replace('-', '_').upper()
        val = sha.get(platform, '')
        if val:
            lines.append(f'{name}_SHA256_{pu}="{val}"')
    lines.append('')
print('\n'.join(lines))
PY
)"

if [ "${1:-}" = "--check" ]; then
  if [ -f "${VERSIONS_ENV}" ] && [ "$(cat "${VERSIONS_ENV}")" = "${generated}" ]; then
    exit 0
  else
    echo "versions.env is out of date — run sync-versions.sh to regenerate" >&2
    exit 1
  fi
fi

printf '%s\n' "${generated}" > "${VERSIONS_ENV}"
echo "Generated ${VERSIONS_ENV} from ${DEPS_YAML}"