#!/usr/bin/env bash
# sync-versions.sh — generate etc/versions.env from etc/deps.yaml.
# deps.yaml is the SINGLE SOURCE OF TRUTH; this produces the runtime
# versions.env that install.sh copies to MINIONS_HOME and lib scripts source.
#
# Usage: scripts/sync-versions.sh [--check]
#   --check: exit non-zero if versions.env would differ (CI guard).
#
#
# Usage: scripts/sync-versions.sh [--check]
#   --check: exit non-zero if versions.env would differ (CI guard).
#
# Requires python3 + pyyaml. If unavailable, exits non-zero with a
# clear message (install.sh ensures this dependency is present).

set -u
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEPS_YAML="${DEPS_YAML:-${REPO_ROOT}/etc/deps.yaml}"
VERSIONS_ENV="${VERSIONS_ENV:-${REPO_ROOT}/etc/versions.env}"
# CI reads .node-version (actions/setup-node), so it must track deps.yaml too.
NODE_VERSION_FILE="${NODE_VERSION_FILE:-${REPO_ROOT}/.node-version}"

[ -f "${DEPS_YAML}" ] || { echo "missing ${DEPS_YAML}" >&2; exit 1; }

# python3 + pyyaml is a hard requirement for generating versions.env.
if ! python3 -c "import yaml" >/dev/null 2>&1; then
  echo "sync-versions.sh: python3 + pyyaml required (install python3-yaml)" >&2
  exit 1
fi

# Generate versions.env content via python3 (yaml module).
generated="$(python3 - "${DEPS_YAML}" <<'PY'
import sys, yaml
data = yaml.safe_load(open(sys.argv[1]))
lines = []
lines.append('# .minions component version lockfile')
lines.append('# Auto-generated by sync-versions.sh from etc/deps.yaml')
lines.append('# Do not edit manually — edit etc/deps.yaml instead')
lines.append('')
for dep in data['dependencies']:
    name = dep['name']
    ver = dep['version']
    lines.append(f'{name}_VERSION="{ver}"')
    sha = dep.get('sha256', {})
    for platform in dep.get('platforms', []):
        pu = platform.replace('-', '_').upper()
        val = sha.get(platform, '')
        if val:
            lines.append(f'{name}_SHA256_{pu}="{val}"')
    lines.append('')
print('\n'.join(lines))
PY
)"

node_version="$(printf '%s\n' "${generated}" | grep '^NODE_VERSION=' | cut -d'"' -f2)"
if [ -z "${node_version}" ]; then
  echo "sync-versions.sh: no NODE dependency in ${DEPS_YAML} — cannot generate .node-version" >&2
  exit 1
fi

if [ "${1:-}" = "--check" ]; then
  rc=0
  if [ -f "${VERSIONS_ENV}" ] && [ "$(cat "${VERSIONS_ENV}")" = "${generated}" ]; then
    :
  else
    echo "versions.env is out of date — run sync-versions.sh to regenerate" >&2
    rc=1
  fi
  if [ -f "${NODE_VERSION_FILE}" ] && [ "$(cat "${NODE_VERSION_FILE}")" = "${node_version}" ]; then
    :
  else
    echo ".node-version is out of date — run sync-versions.sh to regenerate" >&2
    rc=1
  fi
  exit $rc
fi

printf '%s\n' "${generated}" > "${VERSIONS_ENV}"
printf '%s\n' "${node_version}" > "${NODE_VERSION_FILE}"
echo "Generated ${VERSIONS_ENV} and ${NODE_VERSION_FILE} from ${DEPS_YAML}"